/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import com.mpatric.mp3agic.InvalidDataException;
import com.mpatric.mp3agic.UnsupportedTagException;
import goplay.ExtraerTAGS;
import goplay.Reproductor;
import java.io.File;
import java.io.FileFilter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.FilenameFilter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import static javafx.scene.input.KeyCode.T;
import javax.swing.table.DefaultTableModel;
import org.apache.commons.io.filefilter.WildcardFileFilter;

/**
 *
 * @author Fernando
 */
public class prueba extends javax.swing.JFrame {

    /**
     * Creates new form prueba
     */
    //Esto sirve para moldear la tabla
    String col[] = {"Pista", "Artista", "Título", "Álbum", "Año", "Género"};
    DefaultTableModel tableModel = new DefaultTableModel(col, 0);

    public prueba() {
        initComponents();

        this.tablaReproductor.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnImportarCancion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaReproductor = new javax.swing.JTable();
        btnImportarCanciones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnImportarCancion.setText("Importar cancion");
        btnImportarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarCancionActionPerformed(evt);
            }
        });

        tablaReproductor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaReproductor);

        btnImportarCanciones.setText("Importar canciones");
        btnImportarCanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarCancionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnImportarCancion)
                    .addComponent(btnImportarCanciones)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnImportarCancion)
                .addGap(18, 18, 18)
                .addComponent(btnImportarCanciones)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImportarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarCancionActionPerformed
        //Create a file chooser

        String cancion = "";
        final JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo de audio MP3 (*.mp3)", "mp3");
        fc.setFileFilter(filter);
        fc.setAcceptAllFileFilterUsed(false);
        fc.setMultiSelectionEnabled(true);

        File ruta;
        //In response to a button click:
        int returnVal = fc.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            try {
                cancion = fc.getSelectedFile().getCanonicalPath();
                System.out.println(cancion);

                Reproductor player = new Reproductor();
                player.reproducir(cancion);

//            ObjectInputStream entrada = null;
//            try {
//                entrada = new ObjectInputStream(new FileInputStream(ruta));
//                System.out.println(entrada);
//            } catch (FileNotFoundException ex) {
//                Logger.getLogger(prueba.class.getName()).log(Level.SEVERE, null, ex);
//            } catch (IOException ex) {
//                Logger.getLogger(prueba.class.getName()).log(Level.SEVERE, null, ex);
//            }
            } catch (IOException ex) {
                Logger.getLogger(prueba.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnImportarCancionActionPerformed

    private void btnImportarCancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarCancionesActionPerformed

        String toReturn = null;
        String directorio;
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File(".mp3"));
        chooser.setDialogTitle("Elige el directorio de tus canciones");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo de audio MP3 (*.mp3)", "mp3");
        chooser.setFileFilter(filter);
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        //Evitar que hayan otros tipos de archivos
        chooser.setAcceptAllFileFilterUsed(false);
        int choosen = chooser.showOpenDialog(this);
        if (choosen == JFileChooser.APPROVE_OPTION) {
            directorio = chooser.getCurrentDirectory().toString()
                    + "\\" + chooser.getSelectedFile().getName() + "\\";
            System.out.println(directorio);
            Reproductor player = new Reproductor();
            File[] filesInDirectory = player.finder(directorio);

            File dir = new File(directorio);
            FileFilter fileFilter = new WildcardFileFilter("*.mp3");
            File[] files = dir.listFiles(fileFilter);

            //Se crea un nuevo hilo para que el reproductor no laguee :v
            new Thread(new Runnable() {
                public void run() {
                    //Aquí agregamos el proceso a ejecutar.
                    int x = 0;
                    String[] direcciones = new String[files.length];
                    ExtraerTAGS tag = new ExtraerTAGS();
                    for (File file : files) {
                        try {
                            direcciones[x] = file.getAbsolutePath();
                            System.out.println(direcciones[x]);
                            //tag.Informacion(direcciones[x]);
                            tag.Etiquetas(direcciones[x], tableModel);
                            x++;
                        } catch (IOException | UnsupportedTagException | InvalidDataException ex) {
                            Logger.getLogger(prueba.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }

                }
            }).start();

            

        }

//        File[] filesInDirectory = chooser.getCurrentDirectory().listFiles();
//        for (File file : filesInDirectory) {
//            System.out.println(file.getName());
//        }
    }//GEN-LAST:event_btnImportarCancionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prueba.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prueba.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prueba.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prueba.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImportarCancion;
    private javax.swing.JButton btnImportarCanciones;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaReproductor;
    // End of variables declaration//GEN-END:variables
}
