/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import com.mpatric.mp3agic.InvalidDataException;
import com.mpatric.mp3agic.UnsupportedTagException;
import goplay.ExtraerTAGS;
import goplay.Reproductor;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Timer;
import java.util.TimerTask;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import javazoom.jlgui.basicplayer.BasicPlayer;
import javazoom.jlgui.basicplayer.BasicPlayerException;

/**
 *
 * @author Fernando
 */
public class prueba extends javax.swing.JFrame {

    /**
     * Creates new form prueba
     */
    //Esto sirve para moldear la tabla
    ArrayList<String> ubicacionesArrayList = new ArrayList<String>();
    String col[] = {"#", "Artista", "Título", "Álbum", "Año", "Género"};
    DefaultTableModel tableModel = new DefaultTableModel(col, 0);
    String[] canciones;

    //Creando el objeto para reproducir Canciones
    Reproductor player = new Reproductor();
    ExtraerTAGS tag = new ExtraerTAGS();

    //Variables para manegar la reproduccion
    int pos, fila;
    int duracionTotal = 0;
    int duracionActual = 0;
    boolean reproduciendo = false;
    boolean pausado = false;
    boolean detenido = false;

    //Variables para manejar el tiempo
    private Timer tiempo;
    private TimerTask task;
    private int speed = 1000;

    public prueba() {
        initComponents();

        this.tablaReproductor.setModel(tableModel);
        jSlider3.setMinimum(0); //Este es el slider del volumen
        jSlider3.setMaximum(100);
        jSlider3.setValue(50);
        

    }

    //Metodos propios
    private void buscar(String ElementoBusqueda) {
        final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(tableModel);
        this.tablaReproductor.setRowSorter(sorter);
        if (ElementoBusqueda.length() == 0) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + ElementoBusqueda));
        }
    }

    private void etiquetasLabel() {
        this.lblNum.setText(String.valueOf((pos + 1)));
        this.lblArtista.setText(tag.artista);
        this.lblTitulo.setText(tag.titulo);
        this.lblAnhio.setText(tag.anhio);
        this.lblGenero.setText(tag.genero);
    }

    public void IniciarSeekBar(int actual) { // Antes de llamar a este metodo hay que averiguar la duracion total
        tiempo = new Timer();
        duracionActual = actual;
        task = new TimerTask() {
            @Override

            public void run() {
                jSlider1.setMaximum(duracionTotal);
                int tic = 0;
                if (tic % 2 == 0) {
                    duracionActual += 1;
                    // se actualiza el nuevo valor del Slider
                    jSlider1.setValue(duracionActual);
                } else // sino
                {
                    System.out.println("TOC");

                    tic++;

                }
            }
        };
        //se inicia la animacion
        tiempo.schedule(task, 0, speed);
    }

//Detiene la seekbar
    public void DetenerSeekBar() {
        tiempo.cancel();
        task.cancel();
        jSlider1.setValue(0);
    }

    //Volumen
    public void volumen() {
        try {
            double division = 100.0;
            double volumen = jSlider3.getValue() / division;
            player.player.setGain(volumen);
        } catch (BasicPlayerException ex) {
            Logger.getLogger(prueba.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnImportarCancion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaReproductor = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblNum = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblArtista = new javax.swing.JLabel();
        lblAnhio = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnPlay = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jSlider1 = new javax.swing.JSlider();
        btnPausa = new javax.swing.JButton();
        jSlider3 = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnImportarCancion.setText("Importar cancion");
        btnImportarCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarCancionActionPerformed(evt);
            }
        });

        tablaReproductor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaReproductor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaReproductorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaReproductor);

        btnImportarCanciones.setText("Importar canciones");
        btnImportarCanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarCancionesActionPerformed(evt);
            }
        });

        txtBuscar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtBuscarPropertyChange(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        jLabel1.setText("Buscar: ");

        lblNum.setText("jLabel2");

        lblTitulo.setText("jLabel3");

        lblArtista.setText("jLabel4");

        lblAnhio.setText("jLabel5");

        lblGenero.setText("jLabel6");

        lblImagen.setText("labelImagen");

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnPlay.setText("Play");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        jButton3.setText("Siguiente");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Detener");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jSlider1.setValue(0);
        jSlider1.setEnabled(false);
        jSlider1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSlider1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSlider1MouseReleased(evt);
            }
        });

        btnPausa.setText("Pausa");
        btnPausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPausaActionPerformed(evt);
            }
        });

        jSlider3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSlider3MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSlider3MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnImportarCancion)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnImportarCanciones)
                                .addGap(219, 219, 219)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(138, 138, 138)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNum)
                                            .addComponent(lblTitulo)
                                            .addComponent(lblArtista)
                                            .addComponent(lblAnhio)
                                            .addComponent(lblGenero)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(120, 120, 120)
                                        .addComponent(lblImagen))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jButton1)
                        .addGap(42, 42, 42)
                        .addComponent(btnPlay)
                        .addGap(33, 33, 33)
                        .addComponent(jButton3)
                        .addGap(30, 30, 30)
                        .addComponent(jToggleButton1)
                        .addGap(37, 37, 37)
                        .addComponent(btnPausa))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnImportarCancion)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnImportarCanciones))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNum)
                        .addGap(31, 31, 31)
                        .addComponent(lblTitulo)
                        .addGap(45, 45, 45)
                        .addComponent(lblArtista)
                        .addGap(51, 51, 51)
                        .addComponent(lblAnhio)
                        .addGap(49, 49, 49)
                        .addComponent(lblGenero)
                        .addGap(31, 31, 31)
                        .addComponent(lblImagen))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(btnPlay)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3)
                        .addComponent(jToggleButton1)
                        .addComponent(btnPausa)))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImportarCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarCancionActionPerformed
        //Create a file chooser

        String cancion = "";
        final JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo de audio MP3 (*.mp3)", "mp3");
        fc.setFileFilter(filter);
        fc.setAcceptAllFileFilterUsed(false);
        fc.setMultiSelectionEnabled(true);

        //Si le da aceptar luego de elegir el directorio
        int respuesta = fc.showOpenDialog(this);

        if (respuesta == JFileChooser.APPROVE_OPTION) {
            try {
                cancion = fc.getSelectedFile().getCanonicalPath();
                System.out.println(cancion);
                player.reproducir(cancion);

            } catch (IOException ex) {
                Logger.getLogger(prueba.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnImportarCancionActionPerformed

    public boolean boton = false;
    private void btnImportarCancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarCancionesActionPerformed

//        String directorio;
//        JFileChooser chooser = new JFileChooser();
//        chooser.setCurrentDirectory(new java.io.File(".mp3"));
//        chooser.setDialogTitle("Elige el directorio de tus canciones");
//        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo de audio MP3 (*.mp3)", "mp3");
//        chooser.setFileFilter(filter);
//        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
//        //Evitar que hayan otros tipos de archivos
//        chooser.setAcceptAllFileFilterUsed(false);
//        int choosen = chooser.showOpenDialog(this);
//        if (choosen == JFileChooser.APPROVE_OPTION) {
//            directorio = chooser.getCurrentDirectory().toString()
//                    + "\\" + chooser.getSelectedFile().getName() + "\\";
//            System.out.println(directorio);
//
//            File[] filesInDirectory = player.finder(directorio);
//
//            File dir = new File(directorio);
//            FileFilter fileFilter = new WildcardFileFilter("*.mp3");
//            File[] files = dir.listFiles(fileFilter);
        //Probando algo nuevo
        String directorio;
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File(".mp3"));
        chooser.setDialogTitle("Elige el directorio de tus canciones");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo de audio MP3 (*.mp3)", "mp3");
        chooser.setFileFilter(filter);
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        //Evitar que hayan otros tipos de archivos
        chooser.setAcceptAllFileFilterUsed(false);
        int choosen = chooser.showOpenDialog(this);
        if (choosen == JFileChooser.APPROVE_OPTION) {
            boton = false;
            this.btnImportarCanciones.setEnabled(boton);
            directorio = chooser.getCurrentDirectory().toString()
                    + "\\" + chooser.getSelectedFile().getName() + "\\";
            System.out.println(directorio);

            //File[] files = player.finder(directorio);
            try {
                canciones = player.buscarCanciones(directorio);

            } catch (IOException ex) {
                Logger.getLogger(prueba.class
                        .getName()).log(Level.SEVERE, null, ex);
            }

            //FIN DE PROBANDO ALGO NUEVO
            //Se crea un nuevo hilo para que el reproductor no laguee :v
            new Thread(new Runnable() {
                public void run() {
                    boton = true;
                    //Aquí agregamos el proceso a ejecutar.
                    int x = 0;
                    ExtraerTAGS tag = new ExtraerTAGS();
                    String nombreCancion = "";
                    System.out.println("Si funciono va a imprimir todas las direcciones");
                    Collections.addAll(ubicacionesArrayList, canciones);
                    for (long i = 0; i < player.dir.length(); i++) {
                        try {
                            //ubicacionesArrayList.add(canciones[i]);
                            //System.out.println(ubicacionesArrayList.get(x));
                            nombreCancion = player.NombreCancion(ubicacionesArrayList.get(x));
                            tag.Etiquetas(ubicacionesArrayList.get(x), tableModel, (x + 1), nombreCancion); //Se le suma uno para que no empiece en cero
                            x++;
                            nombreCancion = "";

                        } catch (IOException | UnsupportedTagException | InvalidDataException ex) {
                            Logger.getLogger(prueba.class
                                    .getName()).log(Level.SEVERE, null, ex);
                        }
                    }

                }
            }).start();

            //Evitar que las celdas sea editables
            for (int c = 0; c < this.tablaReproductor.getColumnCount(); c++) {
                Class<?> col_class = this.tablaReproductor.getColumnClass(c);
                this.tablaReproductor.setDefaultEditor(col_class, null);        //Quitar la edicion
            }
        }


    }//GEN-LAST:event_btnImportarCancionesActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        //Aqui se haran las busquedas en la tabla
        buscar(this.txtBuscar.getText());
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void tablaReproductorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaReproductorMouseClicked
        //Aqui se reproduce cancion de la tabla al darle click
        int clicks = evt.getClickCount();
        if (clicks == 2) {
            try {
                int row = this.tablaReproductor.getSelectedRow();
                int viewRow = this.tablaReproductor.getSelectedRow();
                int modelRow = this.tablaReproductor.convertRowIndexToModel(viewRow);
                Object valor = tableModel.getValueAt(modelRow, 0);
                pos = (Integer) (valor);
                pos--;
                valor = null;
                System.out.println("La posicion es: " + pos);
                if (player.reproducir(ubicacionesArrayList.get(pos))) {
                    pausado = false;
                    reproduciendo = true;
                    //duracion de la cancion
                    duracionTotal = player.Duracion(ubicacionesArrayList.get(pos));
                    IniciarSeekBar(0); // Empieza la seek a moverse
                    tag.Etiquetas(ubicacionesArrayList.get(pos));
                    etiquetasLabel();//Se les da el valor a los label de las etiquetas de la cancion
                    if (tag.hayImagen) {
                        //ImageIcon icon = new ImageIcon(tag.image);
                        this.lblImagen.setIcon(tag.ImagePeke);//asignandole la imagen al label
                    } else {
                        this.lblImagen.setIcon(null);//quitando la imagen
                    }
                } else {
                    if (this.txtBuscar.getText().equalsIgnoreCase("")) {
                        JOptionPane.showMessageDialog(this, "Lo siento, algo ha salido mal y no puedo reproducir esa canción.\n\nLa quitare de la biblioteca.", "Informacion", 0);
                        //tableModel.removeRow(pos); //Quitando de la JTable
                        tableModel.removeRow(row); //Quitando de la JTable
                        DetenerSeekBar();
                    } else {
                        JOptionPane.showMessageDialog(this, "Lo siento, algo ha salido mal y no puedo reproducir esa canción.\n\nLa quitare de la biblioteca.", "Informacion", 0);
                        row = this.tablaReproductor.convertRowIndexToModel(row);
                        tableModel.removeRow(row);
                        DetenerSeekBar();

                    }
                    //ubicacionesArrayList.remove(pos); // Quitando del ArrayList
//                    ArrayList<String> auxiliar = new ArrayList();
//                    for (int i = pos, j = 0; i < ubicacionesArrayList.size(); i++, j++) {
//                        auxiliar.add(j, ubicacionesArrayList.get((i + 1)));
//                        ubicacionesArrayList.remove(i);// Quitando del ArrayList
//                        ubicacionesArrayList.add(i, auxiliar.get(j));//Reubicando
//                    }
//                    auxiliar = null;

                }

            } catch (ClassCastException | NullPointerException e) {

            } catch (IOException | UnsupportedTagException | InvalidDataException ex) {
                Logger.getLogger(prueba.class
                        .getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedAudioFileException ex) {
                Logger.getLogger(prueba.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_tablaReproductorMouseClicked

    private void txtBuscarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtBuscarPropertyChange
        buscar(this.txtBuscar.getText());
    }//GEN-LAST:event_txtBuscarPropertyChange

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        String nombreCancion = "";

        if (pausado == true) {
            try {
                player.player.resume();
                pausado = false;
                IniciarSeekBar(jSlider1.getValue()); // Empieza la seek a moverse
            } catch (BasicPlayerException ex) {
                Logger.getLogger(prueba.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            int x = 0;
            if (ubicacionesArrayList.size() != 0) {
                // for (int i = x; i < ubicacionesArrayList.size(); x++) {
                if (ubicacionesArrayList.get(x) != null) {
                    if (player.reproducir(ubicacionesArrayList.get(x))) {
                        try {
                            pausado = false;
                            reproduciendo = true;
                            tag.Etiquetas(ubicacionesArrayList.get(x));
                            etiquetasLabel();//Se les da el valor a los label de las etiquetas de la cancion
                            System.out.println(player.Duracion(ubicacionesArrayList.get(x)));

                            //duracion de la cancion
                            duracionTotal = player.Duracion(ubicacionesArrayList.get(x));
                            IniciarSeekBar(0); // Empieza la seek a moverse
                            if (tag.hayImagen) {
                                //ImageIcon icon = new ImageIcon(tag.image);
                                this.lblImagen.setIcon(tag.ImagePeke);//asignandole la imagen al label
                            } else {
                                this.lblImagen.setIcon(null);//quitando la imagen

                            }
                        } catch (IOException ex) {
                            Logger.getLogger(prueba.class
                                    .getName()).log(Level.SEVERE, null, ex);

                        } catch (UnsupportedTagException ex) {
                            Logger.getLogger(prueba.class
                                    .getName()).log(Level.SEVERE, null, ex);

                        } catch (InvalidDataException ex) {
                            Logger.getLogger(prueba.class
                                    .getName()).log(Level.SEVERE, null, ex);

                        } catch (UnsupportedAudioFileException ex) {
                            Logger.getLogger(prueba.class
                                    .getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }

                //}
            } else {
                JOptionPane.showMessageDialog(this, "No hay canciones, intente importar.");
            }
        }

    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnPausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPausaActionPerformed
        try {
            player.player.pause();
            pausado = true;
            reproduciendo = false;
            DetenerSeekBar();
        } catch (BasicPlayerException ex) {
            Logger.getLogger(prueba.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnPausaActionPerformed

    private void jSlider1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider1MouseClicked
        if (jSlider1.getValueIsAdjusting()) {
            try {
                int salto = jSlider1.getValue();
                long seek = (salto * 1000000);
                player.player.seek(seek);
            } catch (BasicPlayerException ex) {
                Logger.getLogger(prueba.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jSlider1MouseClicked

    private void jSlider1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider1MouseReleased
        if (jSlider1.getValueIsAdjusting()) {
            try {
                int salto = jSlider1.getValue();
                long seek = (salto * 1000000);
                player.player.seek(seek);
            } catch (BasicPlayerException ex) {
                Logger.getLogger(prueba.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jSlider1MouseReleased

    private void jSlider3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider3MouseReleased
        volumen();
    }//GEN-LAST:event_jSlider3MouseReleased

    private void jSlider3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider3MouseClicked
        volumen();
    }//GEN-LAST:event_jSlider3MouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        try {  
            DetenerSeekBar();
            player.player.stop();
            detenido = true;
            reproduciendo = false;
        } catch (BasicPlayerException ex) {
            Logger.getLogger(prueba.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DetenerSeekBar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DetenerSeekBar();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prueba.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prueba.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prueba.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prueba.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prueba().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImportarCancion;
    public final javax.swing.JButton btnImportarCanciones = new javax.swing.JButton();
    private javax.swing.JButton btnPausa;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblAnhio;
    private javax.swing.JLabel lblArtista;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblNum;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tablaReproductor;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

}
